# Add this directory as a subdirectory in your main project CMakeLists to include all
# libraries in the build process. You can also add specific libraries by only including
# their specific directory(s).

add_subdirectory(utils_lib)
add_subdirectory(pico_log_lib)
add_subdirectory(uros_utils_lib)
add_subdirectory(freertos_agent_lib)
add_subdirectory(cpp_freertos_alloc_lib)
add_subdirectory(uros_freertos_abstract_lib)